### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by matheustodao** [matheustodao/cine-share#15]
# Discussion

@victorxa4 na troca da linguagem talvez seria melhor um select como tem mais de dois idiomas disponiveis, o que você acha?

# Here
https://github.com/matheustodao/cine-share/blob/main/src/presentation/components/LanguageSwitcher/index.tsx

**Comment by victorxa4** [comment]
Acho uma boa ideia, mas por ser simples vou deixar a assim mesmo,  e o professor só pediu pra deixar a bandeira correspondente com a linguagem atual.

**Comment by matheustodao** [comment]
Okay
