### ISSUE TITLE
Bandeira do Japão

### ISSUE THREAD

**Issue by matheustodao** [matheustodao/cine-share#16]
# Issue
A bandeira do japão quando altera o idioma para japonês não carrega a bandeira

![image](https://github.com/matheustodao/cine-share/assets/52856911/90ec2686-a6a1-40d8-a243-8e91e3760ec5)

@victorxa4

**Comment by victorxa4** [comment]
Comitei com o asset renomeado e o sinal < certo no language switcher.

**Comment by matheustodao** [comment]
Okay
